# Generated by Django 2.1.7 on 2019-12-02 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='object_id',
            field=models.CharField(max_length=50, verbose_name='Key of locked model'),
        ),
    ]
