# Generated by Django 2.1.7 on 2019-12-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locking', '0002_auto_20191202_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='id',
            field=models.CharField(max_length=65, primary_key=True, serialize=False),
        ),
    ]
